### ISSUE TITLE
Entity Subtypes

### ISSUE THREAD

**Issue by tucotuco** [gbif/model-tests#20]
MaterialEntity and DigitalEntity are subtypes of Entity. Both of the classes share having a foreign key to a Collection. Propose to add collectionID to Entity with foreign keys to Collection and remove collectionID from the two subtype classes.

If we choose to change the model for this demo based on the above, we might also aggregate MaterialEntityAssertions and DigitalEntityAssertions into a new EntityAssertion and drop the existing two Assertions tables.

Also, we should remove the remarks as a MaterialEntityAssertion and add an entityRemarks field to Entity for those data.

**Comment by timrobertson100** [comment]
You asked me to share some thoughts on this @tucotuco. I'm not sure I've thought through all the consequences, but here is a start:

+1 to moving common properties to the parent class for the reason that it avoids unnecessary repetition. Implementers will thank us for that.

I think it makes sense to move the assertions to the `entity` table for the simple reason that I can't think of a robust enough explanation of when you would assign them to one or the other. It's effectively an inheritance model (right?) so a record in `entity` and record in `materialEntity` represent the same thing and therefore an assertion against one or the other should be equivalent. It would be clear in cases where an entity record is being _inferred_ without the concrete instance, but having all assertions on `entity` wouldn't cause a problem there anyway. It would mean a merging of any associated controlled vocabularies, but having hierarchical vocabularies would presumably go some way to overcoming any issues.

Following that logic through all common tables and the links to `identification`, `citation` etc can also be put on the `entity` table to reduce table count and complexity. 

This leaves the question - do we need the material and digital entity classes? I suspect the answer is yes, as there will be a schema that we will want to rely on (e.g. modeling things like media type,thumbnails, URLs, sizes, formats etc) and easily query rather than having everything as assertions.

**Comment by tucotuco** [comment]
OK, we agree entirely @timrobertson100. My only real hesitation with respect to converging assertions was the complication it entailed for simple vocabularies shared between the subtypes.

**Comment by tucotuco** [comment]
Version 2 created in /arctos_v2 with 103b535652356e958446a0d88d7307226fde9c09

**Comment by timrobertson100** [comment]
Thanks @tucotuco 
I don't think there is more we want to do now, so I'll close this
